package com.example.hw1_88739.selenium;

// Generated by Selenium IDE
import io.github.bonigarcia.seljup.SeleniumExtension;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

@ExtendWith(SeleniumExtension.class)
public class WeatherTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    private WebElement myDynamicElement;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void weather() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1536, 824));
        driver.findElement(By.linkText("Weather Search")).click();
        driver.findElement(By.id("weatherName")).click();
        assertThat(driver.findElement(By.id("weatherName")).getText(), is("Weather"));
        driver.findElement(By.id("placeName")).click();
        driver.findElement(By.id("placeName")).sendKeys("Viseu,Portugal");
        driver.findElement(By.id("searchButton")).click();
        myDynamicElement = (new WebDriverWait(driver, 20))
                .until(ExpectedConditions.presenceOfElementLocated(By.id("placeWeather")));
        myDynamicElement = (new WebDriverWait(driver, 20))
                .until(ExpectedConditions.presenceOfElementLocated(By.id("weatherText")));
        myDynamicElement = (new WebDriverWait(driver, 20))
                .until(ExpectedConditions.presenceOfElementLocated(By.id("tempVal")));
        myDynamicElement = (new WebDriverWait(driver, 20))
                .until(ExpectedConditions.presenceOfElementLocated(By.id("tempUnits")));
        myDynamicElement = (new WebDriverWait(driver, 20))
                .until(ExpectedConditions.presenceOfElementLocated(By.id("humidity")));
        driver.findElement(By.id("placeWeather")).click();
        assertThat(driver.findElement(By.id("placeWeather")).getText(), is("Place: Viseu,Portugal"));
        driver.findElement(By.id("weatherText")).click();
        //assertThat(driver.findElement(By.id("weatherText")).getText(), is("Weather: Overcast")); //suscetível a mudança
        driver.findElement(By.id("tempVal")).click();
        //assertThat(driver.findElement(By.id("tempVal")).getText(), is("Temperature: 11.91"));//suscetível a mudança
        driver.findElement(By.id("tempUnits")).click();
        assertThat(driver.findElement(By.id("tempUnits")).getText(), is("Temperature units: C"));
        driver.findElement(By.id("humidity")).click();
        //assertThat(driver.findElement(By.id("humidity")).getText(), is("Humidity: 91"));//suscetível a mudança
    }
}

